{application,k3_controller,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{k3_controller_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[k3_controller_app,k3_controller_server,
                        k3_controller_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
